config/routes.rb
Rails.application.routes.draw do
  resources :books
  root "books#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, length: {maximum: 50 }
  validates :price, presence: true,
  numericality: { 
    only_integer: true,
    greater_than: 1
  }
  validates :publish_date, presence: true
  validates :description, presence: true, length: { maximum: 1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: "書籍を登録しました。"
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :price, :publish_date, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%=  form_with model: book, local: true do |form| %>
<%= render "shared/errors", obj: book %>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :price %><br>
    <%= form.number_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :publish_date %><br>
    <%= form.date_field :publish_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, rows: 10, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/books/new.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center">書籍登録</h2>
  <%= render 'form', book: @book %>
</div>

app/views/books/show.html.erb
<div class="col-md-10 offset-md-1 mt-5">
  <%= render "shared/notice" %>
  <h2><%= @book.title %></h2>
  <ul>
    <li><b>価格:</b><%= number_with_delimiter @book.price %>円</li>
    <li><b>発売日:</b><%= @book.publish_date %></li>
  </ul>
  <hr>
  <h4>商品の説明</h4>
  <%= simple_format @book.description %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookShelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/header" %>
  <div class="container">
    <div class="row"></div>
      <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "BookShelf", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Book", new_book_path, class: "nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/shared/_notice.html.erb
<% if flash.notice %>
  <div class="alert alert-success" role="alert">
    <%= flash.notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>